#32 Download apps to deploy
idealista/wildfly-role pull request #33
Opened 2021-05-04 17:08 UTC by jmonterrubio

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions
* Remember to set **idealista:develop** as base branch;

### Description of the Change

### Benefits

### Possible Drawbacks

### Applicable Issues

2021-05-04 17:11 UTC, vicsufer commented
Could you please add this fragment to .travis.yml?
```yml
notifications:
  email:
    if: branch = master
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com
```

2021-05-04 17:17 UTC, sorobon approved these changes

2021-05-04 17:26 UTC, vicsufer requested changes

2021-05-04 17:26 UTC, vicsufer commented on tasks/main.yml
> +  import_tasks: deploy.yml
If you consider to use `import_tasks` here, it's probably best if you replace every `ìnclude` in `main.yml` with `import_tasks` to be symmetric.
I personally prefer using includes, however if so, we should also place tags in every single task in the included file, and considering the nature of those tasks, `import_tasks` here should just work fine.

2021-05-05 07:33 UTC, vicsufer approved these changes

2021-05-05 07:40 UTC, jperera approved these changes

2021-05-05 08:20 UTC, xtianae7 approved these changes

2021-05-05 11:09 UTC, frantsao approved these changes

2021-05-05 11:10 UTC, caldito approved these changes

2021-05-05 11:15 UTC, emepege approved these changes

2021-05-05 13:23 UTC, merged